runtime: nodejs24

handlers:
  - url: /assets/(.*)
    static_files: build/assets/\1
    upload: build/assets/(.*)
    secure: always
  - url: /images/(.*)
    static_files: build/images/\1
    upload: build/images/(.*)
    secure: always
  - url: /(.*\.(json|ico|pdf))$
    static_files: build/\1
    upload: build/.*\.(json|ico|pdf)$
    secure: always
  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1

