name: gcloud-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: 'actions/checkout@v4'

    - uses: actions/setup-node@v3
      with:
        node-version: 22

    - run: npm install
    
    - run: npm run build

    - id: 'auth'
      name: 'Authenticate with Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCT_KEY_JSON }}'

    - id: 'deploy'
      name: 'Application deployment'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        version: 'sole-deployment'
